/* Poly
   Useful
   Lib */

#ifndef __PUL_MACROS_H__
#define __PUL_MACROS_H__

#include <pul/classes.h>
#include <pul/collection.h>

#define PU_LABEL( Text ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Text", \
	PUA_TEXT_STRING, ( PUU32 )( Text ), \
	PUA_TEXT_FIXEDWIDTH, TRUE, \
	0, 0

#define PU_TITLE( Text ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Spacer", \
	PUA_SPACER_HEIGHT, 1, \
	PUA_CONTROL_LABEL, ( PUU32 )Text, \
	PUA_CONTROL_FRAME, PUFRAME_TITLE, \
	0, 0

#define PU_TEXT( Text ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Text", \
	PUA_TEXT_STRING, ( PUU32 )( Text ), \
	PUA_TEXT_CENTERMODE, PU_TEXT_LEFT, \
	0, 0

#define PU_TEXTBUTTON( Text, Msg ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Text", \
	PUA_TEXT_STRING, ( PUU32 )( Text ), \
	PUA_CONTROL_FRAME, PUFRAME_BUTTON, \
	PUA_CONTROL_ISBUTTON, TRUE, 0,\
	PUM_ADDNOTIFICATION, \
		PUNOTIFY_CONDITION_ATTREQUALS, PUA_CONTROL_CLICKED, TRUE, \
		PUNOTIFY_ACTION_APPMSG, Msg, 0 \

#define PU_NARROW_TEXTBUTTON( Text, Msg ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Text", \
	PUA_TEXT_STRING, ( PUU32 )( Text ), \
	PUA_CONTROL_FRAME, PUFRAME_BUTTON, \
	PUA_TEXT_FIXEDWIDTH, TRUE, \
	PUA_CONTROL_ISBUTTON, TRUE, 0,\
	PUM_ADDNOTIFICATION, \
		PUNOTIFY_CONDITION_ATTREQUALS, PUA_CONTROL_CLICKED, TRUE, \
		PUNOTIFY_ACTION_APPMSG, Msg, 0 \

#define PU_SMALL_TEXTBUTTON( Text ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Text", \
	PUA_TEXT_STRING, ( PUU32 )( Text ), \
	PUA_CONTROL_FRAME, PUFRAME_SMALLBUTTON, \
	PUA_CONTROL_ISBUTTON, TRUE, \
	PUA_TEXT_FIXEDWIDTH, TRUE, \
	0, 0

#define PU_THIN_TEXTBUTTON( Text ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Text", \
	PUA_TEXT_STRING, ( PUU32 )( Text ), \
	PUA_CONTROL_FRAME, PUFRAME_SMALLBUTTON, \
	PUA_CONTROL_ISBUTTON, TRUE, \
	0, 0

#define PU_CHECKBOX( ObjId, Label ) \
	PU_ACTION_OBJDEF, ObjId, \
	( PUU32 )"CheckBox", \
	PUA_CHECKBOX_LABEL, ( PUU32 )( Label ), \
	0, 0

#define PU_SET_CHECKBOX( ObjId, Label ) \
	PU_ACTION_OBJDEF, ObjId, \
	( PUU32 )"CheckBox", \
	PUA_CHECKBOX_LABEL, ( PUU32 )( Label ), \
	PUA_CHECKBOX_CHECKED, TRUE, \
	0, 0

#define PU_SPACER \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Spacer", \
	0, 0

#define PU_HORSPACER( Height ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Spacer", \
	PUA_SPACER_HEIGHT, Height, \
	0, 0

#define PU_VERSPACER( Width ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Spacer", \
	PUA_SPACER_WIDTH, Width, \
	0, 0

#define PU_FIXSPACER( Width, Height ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"Spacer", \
	PUA_SPACER_WIDTH, Width, \
	PUA_SPACER_HEIGHT, Height, \
	0, 0


#define PU_HORGROUP \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"HorGroup", 0

#define PU_VERGROUP \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"VerGroup", 0

#define PU_FIXED_VERGROUP \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"VerGroup", \
	PUA_VERGROUP_FIXEDWIDTH, TRUE, \
	PUA_VERGROUP_FIXEDHEIGHT, TRUE, 0

#define PU_LEFT_VERGROUP \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"VerGroup", \
	PUA_VERGROUP_CENTERMODE, PU_VGROUP_LEFT, 0

#define PU_FRAMED_HORGROUP( FrameType, Label ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"HorGroup", \
	PUA_CONTROL_FRAME, FrameType, \
	PUA_CONTROL_LABEL, ( PUU32 )Label, 0

#define PU_FRAMED_VERGROUP( FrameType, Label ) \
	PU_ACTION_OBJDEF, 0, \
	( PUU32 )"VerGroup", \
	PUA_CONTROL_FRAME, FrameType, \
	PUA_CONTROL_LABEL, ( PUU32 )Label, 0

#define PU_ENDGROUP 0


#define PU_WRAPTEXT( Text ) \
		PU_ACTION_OBJDEF, 0, ( PUU32 )"TextArea", \
		PUA_TEXTAREA_READONLY, TRUE, \
		PUA_CONTROL_FRAME, PUFRAME_NONE, \
		PUA_TEXTAREA_FORCEHEIGHT, TRUE, \
		PUA_TEXTAREA_BUFFER, ( PUU32 )Text, \
		0, 0

#define PU_WRAPTEXT_CENTER( Text ) \
		PU_ACTION_OBJDEF, 0, ( PUU32 )"TextArea", \
		PUA_TEXTAREA_READONLY, TRUE, \
		PUA_TEXTAREA_CENTERMODE, PUTA_CENTERMODE_CENTER, \
		PUA_CONTROL_FRAME, PUFRAME_NONE, \
		PUA_TEXTAREA_FORCEHEIGHT, TRUE, \
		PUA_TEXTAREA_BUFFER, ( PUU32 )Text, \
		0, 0


#endif